apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-subconverter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-subconverter
  template:
    metadata:
      labels:
        app: my-subconverter
    spec:
      containers:
      - image: ghcr.io/dunmengjun/my-subconverter:latest
        name: my-subconverter
        ports:
        - containerPort: 25500
          protocol: "TCP"
---
apiVersion: v1
kind: Service
metadata:
  name: my-subconverter
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 25500
  selector:
    app: my-subconverter
